RR-775 - Submit Additional Training through to Have You Worked Before
ministryofjustice/hmpps-education-and-work-plan-ui pull request #583
Opened 2024-04-23 10:53 UTC by nathanrussell-moj-digital

This PR implements the page submission from Additional Training through to Have You Worked Before

2024-04-23 17:16 UTC, leejacobson-moj requested changes
Looks good. Noticed a couple of typos. Will approve as soon as those are updated. 🙂

2024-04-23 17:16 UTC, leejacobson-moj commented on server/routes/induction/update/additionalTrainingUpdateController.test.ts
> +    it('should update InductionDto and redirect to In Prison Work view given shprt question set journey', async () => {
Minor typo:
```suggestion
    it('should update InductionDto and redirect to In Prison Work view given short question set journey', async () => {
```

2024-04-23 17:16 UTC, leejacobson-moj commented on server/routes/induction/create/additionalTrainingCreateController.test.ts
> +    it('should update InductionDto and redirect to In Prison Work view given shprt question set journey', async () => {
Minor typo:
```suggestion
    it('should update InductionDto and redirect to In Prison Work view given short question set journey', async () => {
```

2024-04-24 06:57 UTC, nathanrussell-moj-digital commented on server/routes/induction/update/additionalTrainingUpdateController.test.ts
> +    it('should update InductionDto and redirect to In Prison Work view given shprt question set journey', async () => {
Good spot; fixed 👍

2024-04-24 06:57 UTC, nathanrussell-moj-digital commented on server/routes/induction/create/additionalTrainingCreateController.test.ts
> +    it('should update InductionDto and redirect to In Prison Work view given shprt question set journey', async () => {
Fixed 👍

2024-04-24 08:37 UTC, leejacobson-moj approved these changes
Looks good. Approved 👍

2024-04-24 08:51 UTC, merged